package Gui;

import data.Base;
import data.Reaccion;
import java.io.File;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tobias
 */
public class VentanaPricipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPricipal
     */
    public VentanaPricipal() {
        initComponents();
        Base.load();
    }

    /* 
     * This met Asgard gobernada por Odín.2hod is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lsbinario = new javax.swing.JComboBox<>();
        lsterciario = new javax.swing.JComboBox<>();
        lscuaternario = new javax.swing.JComboBox<>();
        btnListo = new javax.swing.JButton();
        Cbbinario = new javax.swing.JRadioButton();
        cbterciario = new javax.swing.JRadioButton();
        cbcuaternario = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(320, 465));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 242, 242));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesq/image3398.png"))); // NOI18N
        jLabel1.setText("QUIMICAREAC");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 12, 210, 49);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(12, 73, 324, 4);

        lsbinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oxidos ", "Hidruros ", "Hidracidos", "Sales Binarias " }));
        lsbinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsbinarioActionPerformed(evt);
            }
        });
        getContentPane().add(lsbinario);
        lsbinario.setBounds(12, 163, 221, 27);

        lsterciario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oxoacidos ", "Hidroxidos ", "Sal terciaria " }));
        getContentPane().add(lsterciario);
        lsterciario.setBounds(12, 254, 221, 27);

        lscuaternario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sales Cuaternarias " }));
        getContentPane().add(lscuaternario);
        lscuaternario.setBounds(12, 339, 219, 27);

        btnListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesq/flecha.png"))); // NOI18N
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        getContentPane().add(btnListo);
        btnListo.setBounds(212, 399, 95, 52);

        buttonGroup1.add(Cbbinario);
        Cbbinario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Cbbinario.setForeground(new java.awt.Color(254, 254, 254));
        Cbbinario.setText("Compuestos binarios ");
        Cbbinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbinarioActionPerformed(evt);
            }
        });
        getContentPane().add(Cbbinario);
        Cbbinario.setBounds(12, 133, 221, 24);

        buttonGroup1.add(cbterciario);
        cbterciario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cbterciario.setForeground(new java.awt.Color(254, 254, 254));
        cbterciario.setText("Compuesto Terciario");
        getContentPane().add(cbterciario);
        cbterciario.setBounds(12, 218, 221, 24);

        buttonGroup1.add(cbcuaternario);
        cbcuaternario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cbcuaternario.setForeground(new java.awt.Color(254, 254, 254));
        cbcuaternario.setText("Compuestos cuaternarios");
        getContentPane().add(cbcuaternario);
        cbcuaternario.setBounds(12, 309, 219, 24);

        jLabel2.setBackground(new java.awt.Color(254, 202, 202));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Seleccione el compuesto q decea crear...");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 89, 240, 15);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(12, 110, 324, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/serna/Documentos/quimica-master/Quimica/src/imagenesq/fondo-con-ilustraciones-de-molculas_23-2147491176.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 320, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed

        if (Cbbinario.isSelected()) {

            if (lsbinario.getSelectedIndex() == 0) {
                Oxidos aux = new Oxidos();
                aux.setVisible(true);
                this.setVisible(false);

            }
            else if (lsbinario.getSelectedIndex() == 1) {
                Hidruros aux = new Hidruros();
                aux.setVisible(true);
                this.setVisible(false);

            }
            else if (lsbinario.getSelectedIndex() == 2) {
                Hidracidos aux = new Hidracidos();
                aux.setVisible(true);
                this.setVisible(false);

            }
            else if (lsbinario.getSelectedIndex() == 3) {
                SalBinaria aux = new SalBinaria();
                aux.setVisible(true);
                this.setVisible(false);
            }
        } else if (cbterciario.isSelected()) {
            if (lsterciario.getSelectedIndex() == 0) {
                Oxoacidos aux = new Oxoacidos();
                aux.setVisible(true);
                this.setVisible(false);
            }
            else if (lsterciario.getSelectedIndex() == 1) {
                Hidroxidos aux = new Hidroxidos();
                aux.setVisible(true);
                this.setVisible(false);
            }
            else if (lsterciario.getSelectedIndex() == 2) {
                SalTerciaria aux = new SalTerciaria();
                aux.setVisible(true);
                this.setVisible(false);
            }
        } else if (cbcuaternario.isSelected()) {
            if (lscuaternario.getSelectedIndex() == 0) {
                SalCuaternaria aux = new SalCuaternaria();
                aux.setVisible(true);
                this.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "seleciona un tipo de compuesto");

        }

    }//GEN-LAST:event_btnListoActionPerformed

    private void lsbinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsbinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lsbinarioActionPerformed

    private void CbbinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbinarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPricipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cbbinario;
    private javax.swing.JButton btnListo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbcuaternario;
    private javax.swing.JRadioButton cbterciario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> lsbinario;
    private javax.swing.JComboBox<String> lscuaternario;
    private javax.swing.JComboBox<String> lsterciario;
    // End of variables declaration//GEN-END:variables
}
